- Makefile
- circle.yml
- lib/resty/auto-ssl/shell/letsencrypt_hooks
Use a newer version of letsencrypt.sh to fix issues that cropped up on 2016-05-18 due to Let's Encrypt pretty printing their JSON output. See https://github.com/lukas2511/letsencrypt.sh/pull/202
Update build and test process to use newer dependencies.
> Fix compatibility with Let's Encrypt API changes

- README.md
This field is mandatory when 'host' is used.
> Added port-argument to connect

- lib/resty/auto-ssl/utils/start_sockproc.lua
Supersedes #17
I have added here an OR logical operator to verify sockproc state (exit_code) against a boolean value (in this case true).
This became necessary from the context when I noticed that exit_code return a boolean true which did not pass the conditional test on line 6 of start_sockproc.lua.
See this Issue for more details #16
cc/ 
@GUI 
@agentzh
> Refactor the verification of sockproc status

- lib/resty/auto-ssl/storage_adapters/redis.lua
Hello!
For our setup, we would like to use Redis' password authentication as an extra layer of security.
Since this is a trivial change, I took the liberty to implement it for us, and then create this pull request.
Daniël
> Add support for Redis' requirepass option (password auth).

- README.md
also might be nice to mention with the other commonly pre-installed requirements
```
Using http://luarocks.org/repositories/rocks/lua-resty-http-0.09-0.src.rock... switching to 'build' mode
Archive:  /tmp/luarocks_luarocks-rock-lua-resty-http-0.09-0-6181/lua-resty-http-0.09-0.src.rock
inflating: lua-resty-http-0.09-0.rockspec  
creating: lua-resty-http/
creating: lua-resty-http/t/
inflating: lua-resty-http/t/06-simpleinterface.t  
inflating: lua-resty-http/t/08-pipeline.t  
inflating: lua-resty-http/t/11-proxy.t  
inflating: lua-resty-http/t/12-case_insensitive_headers.t  
inflating: lua-resty-http/t/14-host-header.t  
inflating: lua-resty-http/t/05-stream.t  
inflating: lua-resty-http/t/03-requestbody.t  
creating: lua-resty-http/t/cert/
inflating: lua-resty-http/t/cert/test.key …
```
> make in installation requirements

- lib/resty/auto-ssl/storage_adapters/redis.lua
- t/redis.t
My last PR had a bug with domain renewal (sorry about that!). Domains being fetched from redis were not having the Redis key prefix removed causing all renewal checks to fail. This PR fixes that.
> Fix bug in renewal while using a Redis prefix.

- README.md
This PR documents the [`ca`-setting](https://github.com/GUI/lua-resty-auto-ssl/blob/d7041707fe61bcb1624398559d38205a586d7eaf/lib/resty/auto-ssl/init.lua#L63-L66), which can be used to send certificate requests to the [staging environment](https://letsencrypt.org/docs/staging-environment/).
> Document the 'ca' setting

- README.md
- lib/resty/auto-ssl.lua
- lib/resty/auto-ssl/shell/letsencrypt_hooks
- lib/resty/auto-ssl/ssl_providers/lets_encrypt.lua
- t/sanity.t
> WIP: implement new parameter: hook_server_port

- README.md
This just adds a link to the `Test::Nginx` perl module in the README. Makes it a little easier for new people to write tests.
> add note about Test::Nginx module in README

- .luacheckrc
- README.md
- lib/resty/auto-ssl/init_master.lua
- lib/resty/auto-ssl/servers/hook.lua
- lib/resty/auto-ssl/ssl_providers/lets_encrypt.lua
- lib/resty/auto-ssl/utils/shell_execute.lua
- lib/resty/auto-ssl/utils/start_sockproc.lua
- t/file.t
- t/hook_secret.t
- t/memory.t
- t/multiple_workers.t
- t/redis.t
- t/sanity.t
- t/worker_file_permissions.t
> Store hook secret in shared dict, don't overwrite it on reload

- Makefile
- bin/letsencrypt_hooks
- bin/start_sockproc
- lib/resty/auto-ssl/utils/start_sockproc.lua
- t/run_tests
- t/sockproc_file_descriptors.t
When we launch the sockproc process from inside nginx, we explicitly try to clear all extra file descriptors, so nginx doesn't inherit the nginx processes sockets. If sockproc does inherit these sockets, then if nginx gets stopped or restarted, sockproc takes over listening on those sockets, which means nginx can't be started again.
However, the existing implementation of clearing these file descriptors could fail under certain circumstances, leading to nginx being unable to restart. It depends on how nginx is started, but this could reliably fail under this scenario:
- nginx was started under an init script.
- nginx had worker processes running as a less privileged user.
- The user that originally ran the init start command was "cd"ed into a directory that the less privileged nginx …
> Fix sockproc possibly inheriting nginx's sockets/file descriptors

- lib/resty/auto-ssl/jobs/renewal.lua
- lib/resty/auto-ssl/utils/shell_execute.lua
- lib/resty/auto-ssl/utils/start_sockproc.lua
If the `auto_ssl` shared dict ran out of memory, and then nginx were reloaded, then a race condition existed where multiple "sockproc" processes could try to be started at the same time.
While I think this situation would be unlikely to affect a production system in a negative way (since the race condition only occurs during nginx reloads and 1 of the sockproc processes should still succeed and allow things to work), it did lead to some errors being logged, which would intermittently cause our tests to fail (it would crop up on the test following our t/memory.t test, since that next test would be the first reload following our test to explicitly exhaust the memory).
This is fixed by using the `auto_ssl_settings` shared dict for storing the resty-lock details (the lock prevents multiple …
> Fix sockproc startup race conditions after running out of memory

- README.md
- lib/resty/auto-ssl/servers/hook.lua
- t/file.t
- t/hook_server.t
- t/memory.t
- t/multiple_workers.t
- t/redis.t
- t/sanity.t
- t/sockproc_file_descriptors.t
- t/worker_file_permissions.t
This eliminates potential issues if the HTTP POST size to the hook server containing the cert exceeded nginx's default buffer size (which would prevent the hook server from being able to parse the POST args): https://github.com/GUI/lua-resty-auto-ssl/issues/65
Based on some quick tests, it looks like the POST to `/deploy-cert`, containing the certificate chain and private key was the largest POST.  These look to be in the neighborhood of 10KB, while nginx's default `client_body_buffer_size` might be either 8KB or 16KB depending on the exact system architecture. To address this, increase the suggested configuration in the README to 128KB (which is probably overkill, but provides plenty of space in case Let's Encrypt's full certificate chain ever becomes bigger).
This also adds some better …
> Increase the suggested body buffer size for the HTTP hook server

- lib/resty/auto-ssl/ssl_certificate.lua
The allow_domain check might be somewhat costly - involving e.g. an external HTTP request to query a central registry. Make it so that this gets only done before requesting new certificates, not for every HTTPS connection.
> Only check allow_domain when we don't already have a cert

- README.md
- lib/resty/auto-ssl/ssl_certificate.lua
This allows different checks based on the port the request came in.
> Pass ssl_options to allow_domain

- lib/resty/auto-ssl/storage.lua
Those are inconvenient if you don't want to run Redis as LRU cache. We are more interested in not silently discarding any certificates, and scaling Redis with increasing number of domains, so we don't.
If this change is not acceptable, another scheme could be to store the previous (":old") certificate in addition to the current one (":latest"). This way we'd only be storing at most two certificates per domain in Redis, and not a growing number due to renewals.
> Don't store cert backups

- lib/resty/auto-ssl/servers/hook.lua
dehydrated creates 5 files per domain, renewal. While they are not big in size, a seizable number of (sub-) domains can silently exhaust the number of available inodes on a system this way.
> Delete extra cert files after adding the cert to storage

- lib/resty/auto-ssl/jobs/renewal.lua
- lib/resty/auto-ssl/storage.lua
- lib/resty/auto-ssl/storage_adapters/file.lua
- lib/resty/auto-ssl/storage_adapters/redis.lua
This is a second attempt after PR #125. Still testing. CC @brianlund
> Delete certificates that can't be renewed

- README.md
- lib/resty/auto-ssl/ssl_certificate.lua
It is not possible to issue new SSL Certs when service is behind proxy. This solution makes it possible to use proxy and still be able to get SSL Certs.
> Requests for SSL certs handle proxy

- lib/resty/auto-ssl/jobs/renewal.lua
Call allow_domain on renewals, so that it is possible to avoid renewing domains that are not allowed anymore e.g. have expired, dns doesn't resolve anymore etc. using custom code in the allow_domain function.
Thanks to @brianlund who posted this in https://github.com/GUI/lua-resty-auto-ssl/issues/150
This fixes https://github.com/GUI/lua-resty-auto-ssl/issues/101 and at least partially also https://github.com/GUI/lua-resty-auto-ssl/issues/150
> Check whether domains are allowed on renewals

- lib/resty/auto-ssl/jobs/renewal.lua
All other early returns in renew_check_cert drop this lock. Would warrant a comment if this is not needed here.
> Unlock the certificate renewal lock when allow_domain returns false

- lib/resty/auto-ssl/ssl_providers/lets_encrypt.lua
For each issue that doesn't succeed we're still creating three files (cert-*.csr, cert-*.pem, privkey-*.pem) in dehydrated's cert directory that don't get deleted. While they are not big in size, a seizable number of (sub-) domains can this silently exhaust the number of available inodes.
Without this, or a similar patch to the same end, a single certificate that fails to renew (e.g. because the domain has been moved elsewhere) would add 90 files (three per day), which aren't ever deleted. This is compounded by having each subdomain its own certificate.
This is a follow-up to 49256f85c2753d27732a1cadaf7e94cf3d5c5cd8
> Delete local certificate files after dehydrated fails

- lib/resty/auto-ssl/jobs/renewal.lua
The existing code would delete certificates from storage when issuing a new one failed and the old one has already expired. But since the check for allow_domain returns early, we'd never get rid of those for which allow_domain returns false - meaning the renewal checker would continue to check them going forward.
> Purge expired domains that fail the allow_domain check

- lib/resty/auto-ssl.lua
- lib/resty/auto-ssl/utils/has_certificate.lua
We're using this to opportunistically redirect to https in the openresty proxy like so:
```
rewrite_by_lua_block {
local has_cert = auto_ssl:has_certificate(ngx.var.host)
if has_cert then
local https_uri = "https://" .. ngx.var.host .. ngx.var.request_uri
ngx.redirect(https_uri, 301)
end
}
```
_Note: This would still need updates to the Readme etc, but posting for any immediate feedback._
> Add a function for querying whether a certificate exists

- lib/resty/auto-ssl/init_master.lua
start_sockproc requires find:
```
bin/resty-auto-ssl/.start_sockproc-wrapped: line 31: find: command not found
```
Also check for it.
> init_master.lua: check for find
